// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wnlsxxepplhupybqncev.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndubHN4eGVwcGxodXB5YnFuY2V2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODQ4NDQ4NTQsImV4cCI6MjEwMDQyMDg1NH0.pryfZzKobp1UHvUkYaSKQ-HiwArSbk-TKB3g8br0Hdc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== 'undefined' ? localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
  }
});