// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://leocwbwbdxhtygcdskhv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imxlb2N3YndiZHhodHlnY2Rza2h2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODQ4NDQyMjYsImV4cCI6MjEwMDQyMDIyNn0.GpreUX5aE0UzQj0pnqZrAQGJHrgnWCVySiS044bGkF8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== 'undefined' ? localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
  }
});